name: Build APK

on:
  workflow_run:
    workflows: [ "Android CI" ]
    branches:
      - main
    types:
      - completed

jobs:
  build:
    runs-on: macos-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'
          cache: 'gradle'

      - name: Install Homebrew and GNU sed
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/usr/local/bin" >> $GITHUB_PATH
          brew install gnu-sed

      - name: Bump version code
        run: |
          versionCode=$(( $(git rev-list --count HEAD) + 1 ))
          echo "Bumping version code to $versionCode"
          gsed -i "s/versionCode [0-9]*/versionCode $versionCode/" app/build.gradle

      - name: Create local.properties
        run: echo "apiKey=$API_KEY" > local.properties
        env:
          API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/build/outputs/apk/debug/app-debug.apk