name: Android CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'gradle'

      - name: Create local.properties
        run: echo "apiKey=$API_KEY" > local.properties
        env:
          API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run unit tests
        run: ./gradlew test

      - name: Run integration tests
        uses: ReactiveCircus/android-emulator-runner@v2.28.0
        with:
          api-level: 29
          script: ./gradlew connectedCheck